@startuml createCredential
skinparam sequenceMessageAlign right
actor User as user 
participant UI as ui
participant Controller as controller
database Database as db

user -> ui++: Create Credential
ui -> controller++: Create **create Credential request**
controller -> db++: Find issuer DID
db --> controller: Return issuer DID
controller -> controller: Create JWT
controller -> controller: Normalize Credential
controller -> db: Insert Credential
deactivate db
controller --> ui: Return Credential
deactivate controller
ui --> user: Display Credential

@enduml
