@startuml verifyCredential
skinparam sequenceMessageAlign right
actor User as user 
participant UI as ui
participant Controller as controller
database Blockchain as blockchain

user -> ui++: verify Credential
ui -> controller++: verify Credential request
controller -> controller: Get proof from credential
controller -> blockchain++: Resolve DID
blockchain --> controller: Return DID Document
deactivate blockchain
controller -> controller: Check signature from proof
controller -> controller: Check payload data
controller --> ui: Return boolean
deactivate controller
ui --> user: Return boolean
deactivate ui

@enduml
