@startuml verifyPresentation
skinparam sequenceMessageAlign right
actor User as user 
participant UI as ui
participant Controller as controller
database Blockchain as blockchain

user -> ui++: verify Presentation
activate controller
controller --> ui: Generate challenge
controller --> ui: Generate domain
ui --> user: Display requirements
user -> ui: Input presentation
ui -> controller: verify Presentation request
controller -> controller: Get proof from presentation
controller -> blockchain++: Resolve DID
blockchain --> controller: Return DID Document
deactivate blockchain
controller -> controller: Check signature from proof
controller -> controller: Check payload data
controller --> ui: Return boolean
deactivate controller
ui --> user: Return boolean
deactivate ui

@enduml
